services:
  mojimili-laravel:
    ports:
      - 80:80

  adminer:
    restart: always
    image: adminer:latest
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: mojimili-mariadb
